// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-B1snt-p6yv_ND-mdC_QRIzOTLrDh4k',
    appId: '1:757875583003:web:c90cfa5e2757a3d0efb0be',
    messagingSenderId: '757875583003',
    projectId: 'flower-firebase-app',
    authDomain: 'flower-firebase-app.firebaseapp.com',
    storageBucket: 'flower-firebase-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSJTTR85QQp7OEy0bMAnqcFnNCJIbRHj4',
    appId: '1:757875583003:android:c97b06d8fbf2ae56efb0be',
    messagingSenderId: '757875583003',
    projectId: 'flower-firebase-app',
    storageBucket: 'flower-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtXTRYuYtZk4UImlDi6uDxN8WNu6MoNU',
    appId: '1:757875583003:ios:f8d1638d18abe136efb0be',
    messagingSenderId: '757875583003',
    projectId: 'flower-firebase-app',
    storageBucket: 'flower-firebase-app.appspot.com',
    androidClientId:
        '757875583003-1j8785nb1dlhg9lvtn4a8esmlm5o3cbm.apps.googleusercontent.com',
    iosClientId:
        '757875583003-dtfkc24oiomvn4aol9sjaca983gj6soa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMtXTRYuYtZk4UImlDi6uDxN8WNu6MoNU',
    appId: '1:757875583003:ios:765ed80af0a5bba2efb0be',
    messagingSenderId: '757875583003',
    projectId: 'flower-firebase-app',
    storageBucket: 'flower-firebase-app.appspot.com',
    androidClientId:
        '757875583003-1j8785nb1dlhg9lvtn4a8esmlm5o3cbm.apps.googleusercontent.com',
    iosClientId:
        '757875583003-n1eoc8179q7bvoqpp7p4jlpo72ufbt4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerApp.RunnerTests',
  );
}
